### ISSUE TITLE
latex-it  “Convert failed with error code 1” followed instructions but...

### ISSUE THREAD

**Issue by asllearner** [protz/LatexIt#12]
I followed the instructions for a mac given on main page. When I latexit I get 
**\* Found expression $\3 \plus 4$

**\* Generating LaTeX expression:
\documentclass{article}
\usepackage[utf8]{inputenc}
\pagestyle{empty}
\begin{document}
$\3 \plus 4$ %this is where your LaTeX expression goes
\end{document}

I ran /usr/local/bin/latex -output-directory=/Users/me/Library/Caches/TemporaryItems -interaction=batchmode /Users/me/Library/Caches/TemporaryItems/tblatex-1.tex error code 1
LaTeX process returned 1
Proceeding anyway...
Severe error. Missing package?
We left the .tex file there: /Users/me/Library/Caches/TemporaryItems/tblatex-1.tex, try to run latex on it by yourself...
--> Failed, not inserting

message, and in the terminal window I get:

/usr/local/bin/latex: unrecognized option `-output-directory=/Users/me/Library/Caches/TemporaryItems'
Try`/usr/local/bin/latex --help' for more information.

If I latex --help, there is no option named "-output-directory". Maybe this is the error?

**Comment by protz** [comment]
No longer using convert.
