### ISSUE TITLE
Windows XP issues

### ISSUE THREAD

**Issue by sphh** [protz/LatexIt#13]
Hi,

I installed LaTeX It 0.6.2 on Thunderbird 38.1.0 on Windows XP SP 3 with TeX Live 2014.

LaTeX It output is:

    LatexIt! run report...
    
    *** Found expression $\LaTeX$
    
    $PATH is C:\Program Files\Mozilla Thunderbird;C:\Python27\Lib\site-packages\PyQt4;C:\Python27\;C:\Python27\Scripts;C:\Program Files\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\WinMerge;C:\Program Files\Calibre2\;C:\Program Files\MATLAB\MATLAB Compiler Runtime\v713\runtime\win32;C:\Program Files\TortoiseHg\;C:\Program Files\Common Files\Sage SData\;C:\Program Files\Stanford ADL\SU2\bin;C;C:\Program Files\QuickTime\QTSystem\;C:\Python27\DLLs;C:\texlive\2014\bin\win32;C;
    
    *** Generating LaTeX expression:
    \documentclass{article}
    \usepackage[utf8x]{inputenc}
    \pagestyle{empty}
    \begin{document}
    $\LaTeX$ %this is where your LaTeX expression goes
    \end{document}
    
    I ran C:\texlive\2014\bin\win32\latex.exe -output-directory=C:\DOCUME~1\Stephan\LOCALS~1\Temp -interaction=batchmode C:\DOCUME~1\Stephan\LOCALS~1\Temp\tblatex-1.tex error code 1
    LaTeX process returned 1
    Proceeding anyway...
    Severe error. Missing package?
    We left the .tex file there: C:\DOCUME~1\Stephan\LOCALS~1\Temp\tblatex-1.tex, try to run latex on it by yourself...
    --> Failed, not inserting

So I opened the command line and started the command:

    > C:\texlive\2014\bin\win32\latex.exe C:\DOCUME~1\Stephan\LOCALS~1\Temp\tblatex-1.tex
    This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/W32TeX) (preloaded format=latex)
     restricted \write18 enabled.
    entering extended mode
    ! I can't find file `C:/DOCUME'.
    <to be read again>
                       \protect
    <*> C:/DOCUME~
                  1/Stephan/LOCALS~1/Temp/tblatex-1.tex
    (Press Enter to retry, or Control-Z to exit)
    Please type another input file name:

Could you please update the paths for this type of installation. Thanks!

Cheers,
Stephan

**Comment by SuperGianchi** [comment]
Well, I experience exactly the same problem with TeX Live 2014, Windows 8 and Thunderbird 38.2.0.
By the way, now TeX Live 2015 is available ;)

I hope you'll fix the problem: the LaTeXit! idea is great!!!

**Comment by msprotz** [comment]
That's very weird, and I have no idea what's happening. Did you find a way to fix this while you're in the command prompt?

**Comment by SuperGianchi** [comment]
Hi Jonathan,

Sorry for my late reply.

Well I cannot say that I'm an expert, however this is the LatexIt! error
-----------------
LatexIt! run report...

*** Found expression $$x$$
LaTeX process returned 1
Proceeding anyway...
Severe error. Missing package?
We left the .tex file there: C:\Users\GIANCA~1\AppData\Local\Temp\tblatex-1.tex, try to run latex on it by yourself...
-----------------

and this is the C:\Users\Giancarlo\AppData\Local\Temp\texput.log
-----------------
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/W32TeX) (preloaded format=latex 2014.8.28)  1 OCT 2015 21:04
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**C:/Users/GIANCA~1/AppData/Local/Temp/tblatex-1.tex
! Emergency stop.
<to be read again>
                   \protect
<*> C:/Users/GIANCA~
                    1/AppData/Local/Temp/tblatex-1.tex
*** (job aborted, file error in nonstop mode)

 
Here is how much of TeX's memory you used:
 5 strings out of 493109
 191 string characters out of 6138472
 52954 words of memory out of 5000000
 3569 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 3i,0n,0p,1b,6s stack positions out of 5000i,500n,10000p,200000b,80000s
No pages of output.
-----------------

As Stephan, if I write in the TeX Live command-line
-----------------
Microsoft Windows [Versione 6.2.9200]
(c) 2012 Microsoft Corporation. Tutti i diritti riservati.

C:\Users\Giancarlo>C:\texlive\2014\bin\win32\latex.exe C:\Users\GIANCA~1\AppData
\Local\Temp\tblatex-1.tex
-----------------

the output is
-----------------
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/W32TeX) (preloaded
 format=latex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `C:/Users/GIANCA'.
<to be read again>
                   \protect
<*> C:/Users/GIANCA~
                    1/AppData/Local/Temp/tblatex-1.tex
(Press Enter to retry, or Control-Z to exit)
Please type another input file name:
-----------------

So I thought to avoid the ~ character. Writing
-----------------
Microsoft Windows [Versione 6.2.9200]
(c) 2012 Microsoft Corporation. Tutti i diritti riservati.

C:\Users\Giancarlo>C:\texlive\2014\bin\win32\latex.exe C:\Users\Giancarlo\AppData\Local\Temp\tblatex-1.tex
-----------------
everything works!!! this is the output:
-----------------
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/W32TeX) (preloaded
 format=latex)
 restricted \write18 enabled.
entering extended mode
(c:/Users/Giancarlo/AppData/Local/Temp/tblatex-1.tex
LaTeX2e <2014/05/01>
Babel <3.9k> and hyphenation patterns for 79 languages loaded.
(c:/texlive/2014/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(c:/texlive/2014/texmf-dist/tex/latex/base/size10.clo))
(c:/texlive/20





14/texmf-dist/tex/latex/base/inputenc.sty
(c:/texlive/2014/texmf-dist/tex/latex/ucs/utf8x.def))
(c:/texlive/2014/texmf-dist/tex/latex/ucs/ucs.sty
(c:/texlive/2014/texmf-dist/tex/latex/ucs/data/uni-global.def))
(c:/texlive/2014/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(c:/texlive/2014/texmf-dist/tex/latex/amsmath/amstext.sty
(c:/texlive/2014/texmf-dist/tex/latex/amsmath/amsgen.sty))
(c:/texlive/2014/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(c:/texlive/2014/texmf-dist/tex/latex/amsmath/amsopn.sty))
(c:/texlive/2014/texmf-dist/tex/latex/amsfonts/amssymb.sty
(c:/texlive/2014/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(c:/texlive/2014/texmf-dist/tex/latex/jknapltx/mathrsfs.sty)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/palatino.sty)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/mathpazo.sty) (./tblatex-1.aux)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/ot1ppl.fd)
(c:/texlive/2014/texmf-dist/tex/latex/ucs/ucsencs.def)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/omlzplm.fd)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/omszplm.fd)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/omxzplm.fd)
(c:/texlive/2014/texmf-dist/tex/latex/jknapltx/ursfs.fd)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/ot1zplm.fd) [1] (./tblatex-1.aux)
)
Output written on tblatex-1.dvi (1 page, 212 bytes).
Transcript written on tblatex-1.log.

C:\Users\Giancarlo>
-----------------

:)

If you are interested in, I've attached the output written in C:\Users\Giancarlo\tblatex-1.log
(it seems that there are some problems and I cannot attach the file; let me know if you need it)

Well, I presume that every TeX Live users experiment the same error...

Finally, thanks for this useful add and good luck with LatexIt! ;)

**Comment by SuperGianchi** [comment]
Hi Jonathan,

Sorry for my late reply.

Well I cannot say that I'm an expert, however this is the LatexIt! error

-----------------
LatexIt! run report...

*** Found expression $$x$$
LaTeX process returned 1
Proceeding anyway...
Severe error. Missing package?
We left the .tex file there: C:\Users\GIANCA~1\AppData\Local\Temp\tblatex-1.tex, try to run latex on it by yourself...
-----------------

and this is the C:\Users\Giancarlo\AppData\Local\Temp\texput.log

-----------------
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/W32TeX) (preloaded format=latex 2014.8.28)  1 OCT 2015 21:04
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**C:/Users/GIANCA~1/AppData/Local/Temp/tblatex-1.tex
! Emergency stop.
<to be read again>
                   \protect
<*> C:/Users/GIANCA~
                    1/AppData/Local/Temp/tblatex-1.tex
*** (job aborted, file error in nonstop mode)

 
Here is how much of TeX's memory you used:
 5 strings out of 493109
 191 string characters out of 6138472
 52954 words of memory out of 5000000
 3569 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 3i,0n,0p,1b,6s stack positions out of 5000i,500n,10000p,200000b,80000s
No pages of output.
-----------------

As Stephan, if I write in the TeX Live command-line
-----------------
Microsoft Windows [Versione 6.2.9200]
(c) 2012 Microsoft Corporation. Tutti i diritti riservati.

C:\Users\Giancarlo>C:\texlive\2014\bin\win32\latex.exe C:\Users\GIANCA~1\AppData
\Local\Temp\tblatex-1.tex
-----------------

the output is
-----------------
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/W32TeX) (preloaded
 format=latex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `C:/Users/GIANCA'.
<to be read again>
                   \protect
<*> C:/Users/GIANCA~
                    1/AppData/Local/Temp/tblatex-1.tex
(Press Enter to retry, or Control-Z to exit)
Please type another input file name:
-----------------

So I thought to avoid the ~ character. Writing
-----------------
Microsoft Windows [Versione 6.2.9200]
(c) 2012 Microsoft Corporation. Tutti i diritti riservati.

C:\Users\Giancarlo>C:\texlive\2014\bin\win32\latex.exe C:\Users\Giancarlo\AppData\Local\Temp\tblatex-1.tex
-----------------

everything works!!! this is the output:
-----------------
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/W32TeX) (preloaded
 format=latex)
 restricted \write18 enabled.
entering extended mode
(c:/Users/Giancarlo/AppData/Local/Temp/tblatex-1.tex
LaTeX2e <2014/05/01>
Babel <3.9k> and hyphenation patterns for 79 languages loaded.
(c:/texlive/2014/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(c:/texlive/2014/texmf-dist/tex/latex/base/size10.clo))
(c:/texlive/2014/texmf-dist/tex/latex/base/inputenc.sty
(c:/texlive/2014/texmf-dist/tex/latex/ucs/utf8x.def))
(c:/texlive/2014/texmf-dist/tex/latex/ucs/ucs.sty
(c:/texlive/2014/texmf-dist/tex/latex/ucs/data/uni-global.def))
(c:/texlive/2014/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(c:/texlive/2014/texmf-dist/tex/latex/amsmath/amstext.sty
(c:/texlive/2014/texmf-dist/tex/latex/amsmath/amsgen.sty))
(c:/texlive/2014/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(c:/texlive/2014/texmf-dist/tex/latex/amsmath/amsopn.sty))
(c:/texlive/2014/texmf-dist/tex/latex/amsfonts/amssymb.sty
(c:/texlive/2014/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(c:/texlive/2014/texmf-dist/tex/latex/jknapltx/mathrsfs.sty)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/palatino.sty)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/mathpazo.sty) (./tblatex-1.aux)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/ot1ppl.fd)
(c:/texlive/2014/texmf-dist/tex/latex/ucs/ucsencs.def)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/omlzplm.fd)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/omszplm.fd)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/omxzplm.fd)
(c:/texlive/2014/texmf-dist/tex/latex/jknapltx/ursfs.fd)
(c:/texlive/2014/texmf-dist/tex/latex/psnfss/ot1zplm.fd) [1] (./tblatex-1.aux)
)
Output written on tblatex-1.dvi (1 page, 212 bytes).
Transcript written on tblatex-1.log.

C:\Users\Giancarlo>
-----------------

:)

If you are interested in, I've attached the output written in C:\Users\Giancarlo\tblatex-1.log
(it seems that there are some problem; please, let me know if you need the attachment)

Well, I presume that every TeX Live users experiment the same error...

Finally, thanks for this useful add and good luck with LatexIt! ;)

**Comment by SuperGianchi** [comment]
P.S.
sorry for the bold: it's the markdown. When there are*characters it writes in bold; I don't know how to avoid this behaviour...

**Comment by sphh** [comment]
Hi Jonathan,

A quick search brought up this link with some options how to deal with 
8.3 file names on Windows: 
http://tex.stackexchange.com/questions/183568/using-8-3-path-names-with-pdflatex

But I am sure you have found it yourself already.....

Thanks for looking into this issue again!

Stephan

**Comment by protz** [comment]
I guess then the solution is to upgrade to texlive 2015?

~ jonathan

**Comment by SuperGianchi** [comment]
Yes it is!! I've just installed TeX Live 2015 and now I can use LatexIt! too :)

**Comment by sphh** [comment]
I installed TeX Live 2015 over night and after autodetecting the binaries I can confirm that it works.

Jonathan, it might be worth to make a note that you need TeX Live **2015** on Windows.

Stephan.
