### ISSUE TITLE
Severe error. Missing package?

### ISSUE THREAD

**Issue by theodore-norvell** [protz/LatexIt#14]
I got the following error message.  Using MacTex 2015 and TBird 38.3 with LatexIt 0.6.2 This is on MacOS 10.11 (OS X El Capitan)

> *** Found expression $E = mc^2$
> LaTeX process returned 1
> Proceeding anyway...
> Severe error. Missing package?
> We left the .tex file there: /Users/theo/Library/Caches/TemporaryItems/tblatex-1.tex, try to run latex on > it by yourself...

I tried cd'ing to the directory and ran the following command

> n060h002:TemporaryItems theo$ /usr/local/texlive/2015/bin/x86_64-darwin/latex -output-directory=. -interaction=batchmode tblatex-1.tex 

which worked and produced a new .dvi file just fine.

**Comment by protz** [comment]
is your path to latex correct?

~ jonathan

**Comment by theodore-norvell** [comment]
Yikes.  It was not!  I was careful about the directory but picked the wrong file!

Thanks for your help.   It's a wonderful add-on.

Theodore Norvell
