### ISSUE TITLE
Output colors

### ISSUE THREAD

**Issue by bremenpl** [protz/LatexIt#16]
Hello there,
First of all thank you for the great addon.
I have a question regarding the color of the output formulas. I have noticed that they are always black, and my thunderbird is white text on a black background. In that case I dont see anything. I am also aware that if the color of the equation text would be white my recipients wont see anything. With text its esier as it has no color attached to it as its plain text. 
Can you think of any workaround? I would appreciate all help.

**Comment by protz** [comment]
Hello,

You would have to customize the latex template to fix the colors in the addon's options.
