### ISSUE TITLE
Latex It! button fails and /tmp/tblatex-1.tex is empty

### ISSUE THREAD

**Issue by pimartinet** [protz/LatexIt#17]
Hello!
I tried the 'Latex It!' button with this message:

> Hello $\LaTeX$

And it fails with:

> LatexIt! run report...
> 
> **\* Found expression $\LaTeX$
> LaTeX process returned 1
> Proceeding anyway...
> Severe error. Missing package?
> We left the .tex file there: /tmp/tblatex-1.tex, try to run latex on it by yourself...

But the file /tmp/tblatex-1.tex is empty.

It works fine when I use 'insert complex latex' from the menu so I also tried:

> Hello
> $
> \documentclass{article}
> \usepackage[utf8]{inputenc}
> \begin{document}
> \LaTeX
> \end{document}
> $

But the expression isn't detected.

**Comment by pascalcpp** [comment]
Never mind, I found what's wrong: I had changed the template and forgot to add __REPLACEME__ in it.
