### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by lilblake91** [protz/LatexIt#18]
Hopefully this isn't something obvious that I'm overlooking, but I installed Latexit, Imagemagick, and Ghostscript as needed but there seems to be an error with convert.exe.

Also the autodetect option doesn't find convert.exe so I have to go in my directory and manually select it; this leads me to believe I might have the wrong version of imagemagick or something (I made sure to get the 32 bit version).

LatexIt! run report...

**\* Found expression $a+b$

$PATH is C:\Program Files (x86)\Mozilla Thunderbird;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\MATLAB\R2015b\bin;C:\Users\Blake\AppData\Roaming\MiKTeX\2.9\miktex\bin\x64\;C:\Users\Blake\AppData\Local\Microsoft\WindowsApps;

**\* Generating LaTeX expression:
\documentclass{article}
\usepackage[utf8x]{inputenc}
\pagestyle{empty}
\begin{document}
$a+b$ %this is where your LaTeX expression goes
\end{document}

I ran C:\Program Files\MiKTeX 2.9\miktex\bin\x64\latex.exe -output-directory=C:\Users\Blake\AppData\Local\Temp -interaction=batchmode C:\Users\Blake\AppData\Local\Temp\tblatex-1.tex error code 0
I ran C:\Program Files\MiKTeX 2.9\miktex\bin\x64\dvips.exe -o C:\Users\Blake\AppData\Local\Temp\tblatex-1.ps -E C:\Users\Blake\AppData\Local\Temp\tblatex-1.dvi
I ran C:\Program Files (x86)\ImageMagick-7.0.3-Q16\convert.exe -units PixelsPerInch -density 150 C:\Users\Blake\AppData\Local\Temp\tblatex-1.ps -trim C:\Users\Blake\AppData\Local\Temp\tblatex-1.png
convert failed with error code 1. Aborting.
Possible explanations include:
- you're running Windows, and you didn't install Ghostscript
- you're running OSX, and you didn't launch Thunderbird from a Terminal

Please see http://github.com/protz/LatexIt/wiki
--> Failed, not inserting

**Comment by protz** [comment]
what is the error if you run convert yourself?

**Comment by Abunux** [comment]
Hi 
i've just had the same issue (on Linux) and found the solution here : https://stackoverflow.com/questions/42928765/convertnot-authorized-aaaa-error-constitute-c-readimage-453
Problems comes from ImageMagick policy : 
Edit the file  /etc/ImageMagick-6/policy.xml as admin (sudo nano /etc/ImageMagick-6/policy.xml)
At the end change the line:
`<policy domain="coder" rights="none" pattern="PS" />`  
To : 
 `<policy domain="coder" rights="read|write" pattern="PS" />`
  
And it worked for me

PS : This Issue is old but maybe my solution can help others who google it
PPS : Thanks for this wonderful extension !!

**Comment by protz** [comment]
Wow. Can you add this to the wiki?

**Comment by sphh** [comment]
This might be closed as well, because we switched from .tex --> .dvi --> .ps --> .png to .tex --> .dvi --> .png and we don't use `convert` anymore ...
