### ISSUE TITLE
Severe error

### ISSUE THREAD

**Issue by macthecadillac** [protz/LatexIt#20]
Thunderbird version: 52.4.0 (64bit)
Operating system: Debian 9.2

Run report:
```
*** Found expression $E = mc^2$

$PATH is /home/mac/.cargo/bin:/home/mac/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

*** Generating LaTeX expression:
\documentclass[9pt]{article}
\usepackage[utf8x]{inputenc}
%\usepackage[adobe-utopia]{mathdesign}
\usepackage[erewhon,vvarbb,bigdelims]{newtxmath}
\usepackage{amsmath,amssymb}
\pagestyle{empty}
\everymath{\displaystyle}
\begin{document}
$E = mc^2$ %this is where your LaTeX expression goes
\end{document}

I ran /usr/bin/latex -output-directory=/tmp -interaction=batchmode /tmp/tblatex-1.tex error code 1
LaTeX process returned 1
Proceeding anyway...
Severe error. Missing package?
We left the .tex file there: /tmp/tblatex-1.tex, try to run latex on it by yourself...
--> Failed, not inserting
```

I followed the trouble shooting guide and didn't encounter any errors. I repeated the steps with `tblatex-1.tex` generated by LaTexIt and again did not encounter any errors. In fact, running `/usr/bin/latex -output-directory=/tmp -interaction=batchmode /tmp/tblatex-1.tex` manually gives an exit code of 0.

Here is the terminal output when running LaTexIt in an instance of Thunderbird started from the terminal:
```
[Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsILocalFile.remove]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: chrome://tblatex/content/main.js :: run_latex/< :: line 191"  data: no]
run_latex/<@chrome://tblatex/content/main.js:191:11
run_latex@chrome://tblatex/content/main.js:188:7
replace_latex_nodes/<@chrome://tblatex/content/main.js:330:28
replace_latex_nodes@chrome://tblatex/content/main.js:325:45
tblatex.on_latexit@chrome://tblatex/content/main.js:377:7
oncommand@chrome://messenger/content/messengercompose/messengercompose.xul:1:1
```
Thanks

**Comment by e-c-d** [comment]
I just spent 4h going crazy tracking this one down. First I thought it was some API change in Thunderbird, but `strace` showed that the process wasn't getting launched at all even with simple hand-crafted process calls! So maybe it was a regression in Debian's Thunderbird build (nope).

Try `sudo apparmor_status` and see if thunderbird is under "enforce mode". If it is, then the rather restrictive apparmor profile is preventing it from calling `latex`. If that is the case, you may consider [disabling the profile](https://help.ubuntu.com/community/AppArmor#Disable_one_profile).

**Comment by macthecadillac** [comment]
Disabling the thunderbird apparmor profile worked like a charm. Thanks

**Comment by protz** [comment]
Could you add this information to the wiki? This seems very useful.
