### ISSUE TITLE
Thunderbird 52 -- Button doesn't show

### ISSUE THREAD

**Issue by klieret** [protz/LatexIt#21]
Hi,

I just installed the extension (tried both with the one from this repository and the one from the Mozilla Site) but the extension's button in the Write Message window does not show up.

I have installed all of the required packages. I also ran tunderbird from the cli with the debug option enabled in this add-on's preference window, but there are no error messages. The paths to LaTeX, Convert & Co are correct.

Thunderbird --version:  Thunderbird 52.5.0
tex --version: TeX 3.14159265 (TeX Live 2015/Debian)
Ubuntu 16.04.3 LTS

It's a really nice add-on, would love to have it working!

Best regards,
Kilian

**Comment by sphh** [comment]
The button is not added automatically. Please see this [solution](https://github.com/protz/LatexIt/issues/5#issuecomment-658753) in #5.

The online description for the add-on describes the procedure as: "To use this add-on, just right-click on the toolbar when composing an email, and add the "Latex It!" button to the toolbar (see the first screenshot)."

I hope it works and you can close this issue.

**Comment by klieret** [comment]
Thank you for your help @sphh !  So sorry that I didn't read the description carefully enough/figure that out by myself. It's an incredibly useful addon and it works like a charm now!
