### ISSUE TITLE
error code 1

### ISSUE THREAD

**Issue by Neocurve** [protz/LatexIt#22]
I have error 1 on mac and changing error as I change the convert path.

*** Generating LaTeX expression:
\documentclass{article}
\usepackage[utf8x]{inputenc}
\pagestyle{empty}
\begin{document}
$$a+b$$ %this is where your LaTeX expression goes
\end{document}

I ran /Library/TeX/texbin/latex -output-directory=/var/folders/xt/201bpzbs6_x1dfpdpjzhjx1m0000gn/T -interaction=batchmode /var/folders/xt/201bpzbs6_x1dfpdpjzhjx1m0000gn/T/tblatex-1.tex error code 0
I ran /Library/TeX/texbin/dvips -o /var/folders/xt/201bpzbs6_x1dfpdpjzhjx1m0000gn/T/tblatex-1.ps -E /var/folders/xt/201bpzbs6_x1dfpdpjzhjx1m0000gn/T/tblatex-1.dvi
Severe error. Missing package?
We left the .tex file there: /var/folders/xt/201bpzbs6_x1dfpdpjzhjx1m0000gn/T/tblatex-1.tex, try to run latex on it by yourself...
--> Failed, not inserting

I'm running Mac OSX high seirra

**Comment by protz** [comment]
What is the error if you run the second command yourself?

**Comment by sphh** [comment]
Could this be closed, because we switched from generating a .ps and then a .png to making the .png directly from the .dvi?
