### ISSUE TITLE
write18 issue in Ubuntu

### ISSUE THREAD

**Issue by bilboinamerica** [protz/LatexIt#29]
Under Ubuntu, `dlatex -output-directory /tmp -interaction=batchmode test.tex `
gives the error `restricted \write18 enabled. entering extended mode`
Without the batchmode part the command works fine.

EDIT: This helped:
https://tex.stackexchange.com/questions/471433/thunderbird-latexit-extension-convert-failed-with-error-code-1
With the change in Imagemagick I still get `LaTeX process returned 1` but the e-mail looks fine.

**Comment by protz** [comment]
This is solved by removing the reliance on convert.
