### ISSUE TITLE
Problem running on Ubuntu

### ISSUE THREAD

**Issue by Reylocnier** [protz/LatexIt#30]
Hi,

I have always used LaTeX-It under Windows with MiKTeX without any problem and today I can't get it to work under Ubuntu.
I'm under Ubuntu 18.04.1 LTS  and with Thunderbird 60.4.0 64 bits. I installed texlive-full and checked that tex-live-extra is well installed. There is no problem in the autodetection window either.

![image](https://user-images.githubusercontent.com/47411440/52847574-d7b76600-310c-11e9-905b-a9fc50bf4520.png)

But when I try to use it I have the classic error message : 

![image](https://user-images.githubusercontent.com/47411440/52847659-11886c80-310d-11e9-8caf-f9726bc7ed5e.png)

Does anyone have an idea that can fix my problem?

**Comment by sphh** [comment]
The "problem" seems to be the ImageMagick security policy https://www.imagemagick.org/script/security-policy.php. It looks like some distributions (I use Linux Mint 19) tighten the security by forbidding postscript files to be converted. A quick fix is to edit `/etc/ImageMagick-6/policy.xml` and change this line
```xml
  <policy domain="coder" rights="none" pattern="PS" />
```
to
```xml
  <policy domain="coder" rights="read" pattern="PS" />
```

A possible long-term solution would be to use another `dvi` to `png` converter, e.g. `dvipng`.

**Comment by protz** [comment]
Closing in favor of #4 and the fact that it's documented on the wiki (https://github.com/protz/LatexIt/wiki). Any help in switching to dvipng would be most welcome.

Thanks,

jonathan
