### ISSUE TITLE
texlive issue with DOS-style paths

### ISSUE THREAD

**Issue by phaedo314** [protz/LatexIt#32]
I have texlive 2018 and its latex.exe fails because does not recognize DOS-style paths (e.g. C:\Users\LONGNA~1 instead of C:\Users\Longname )

Suggestion: make sure LatexIt expands file paths in long-name format

Also: allow command line parameters in Options executable file locations

**Comment by protz** [comment]
the reason for DOS-style paths was that a bunch of programs would fail if passed paths that contained spaces... maybe this has been fixed now? 

in any case, I would happily take a pull request for this

Thanks,

Jonathan

**Comment by phaedo314** [comment]
I don't know if texlive has fixed this issue, I had to create a wrapper latex.exe to circumvent this problem.  Maybe try to use LatexIt with TexLive 2019 and if it fails you know the issue
Thanks
p.

**Comment by sphh** [comment]
See also #56, where the same issue is reported with MiKTeX.

Maybe it's time to drop DOS-style paths?

**Comment by protz** [comment]
if someone can confirm it's fine on windows, I'm all for it

**Comment by urigrupel** [comment]
I can do additional testing on Windows 10 + MiKTeX if you need them. Just let me know what to check.

**Comment by sphh** [comment]
This should be sorted with the PRs #81 and #82 now merged.
