### ISSUE TITLE
Why Ghostscript is necessary? (Thunderbird Portable)

### ISSUE THREAD

**Issue by loicreynier** [protz/LatexIt#33]
(this is not really an issue)

Hi,

I use Thunderbird portable to send emails from different computers (work, school, home...) and I would like to add LaTeX-It to this version. Since Windows is everywhere I use the Windows version of Thunderbird portable.

I have MiKTeX and ImageMagick portable on my USB key so there is no problem for the path to _latex_, _dvips_ and _convert_ executable. The problem is _GhostScript_. I found a [portable a version of it](https://portableapps.com/apps/utilities/ghostscript_portable), distributed by PortableApps.
I don't really understand when the program need _GhostScript_ and I would like to understand in order to make this portable version work.

Thank you in advance for your help.

**Comment by sphh** [comment]
It looks like imagemagick's `convert` command needs _GhostScript_.

You might want to try the approach outlined in https://github.com/protz/LatexIt/issues/4#issuecomment-502653553 or wait for @protz to merge #35 and issue a new release...
