### ISSUE TITLE
Baseline alignment of images

### ISSUE THREAD

**Issue by sphh** [protz/LatexIt#36]
As @eudoxos mentioned in https://github.com/protz/LatexIt/issues/4#issuecomment-2014962, it should be possible to align the equations correctly when using `dvipng` (#35). The way to do it is as follows:

1. Have the LaTeX package `preview` available.
2. Insert `\usepackage[active,textmath]{preview}` into the preamble of the LaTeX document.
3. Run `dvipng` with the option `--depth`.
4. Parse the output of the command for the `depth` value (a typical output is
    ```
    This is dvipng 1.15 Copyright 2002-2015 Jan-Ake Larsson
    [1 depth=4]
    ```
5. Return the depth value (in the above case `4`) from `main.js:run_latex()` in addition to the values already returned.
6. In `content/main.js` replace all `img.style = "vertical-align: middle"` with `img.style = "vertical-align: -<depth>px"` (`<depth>` is the value returned by `dvipng` and needs a `-` sign in front of it).

That is pretty straightforward.

The problem is the step 4, because it looks like that the it is not possible to capture the output of an external command in Thunderbird (https://stackoverflow.com/questions/10215643/how-to-execute-a-windows-command-from-firefox-addon#answer-10216452). However it is possible to redirect the standard output into a temporary file and parse that file. But this opens another can of worms (and a bag of possible bug reports and bad comments): You need to call the command in an external shell (or LatexIt! must call a special script doing the redirection, which should also be avoided).

**Does anybody know how to get hold of the output of an external command (in our case `dvipng`) without using a shell?**

**Comment by protz** [comment]
I don't know of any way to do that but Mozilla folks might have an answer on IRC in #gecko or #addons 

Otherwise, I would be fine with taking in a pull request that detects the os, then executes `cmd /c` (via COMSPEC) or `/bin/sh -c`  -- I think it's an okay solution and would solve the problem nicely.

Thanks,

Jonathan
