### ISSUE TITLE
Going to the preference screen of LatexIt! changes the window size

### ISSUE THREAD

**Issue by sphh** [protz/LatexIt#37]
When you call up the preference screen of LatexIt! from the add-ons page, a new tab opens and the size of the window is changed. Maybe LatexIt! should open a separate configuration window and my Thunderbird forces this to be a tab. In the first case (separate window) the size change makes sense, in the second case (new tab) it is simply annoying.

My Thunderbird is 60.7.0 (64-bit) on Linux Mint 19.1

**Comment by protz** [comment]
Hi @sphh 

Is this still an issue? In Thunderbird 68 I feel like the only way to find the addon's options is to use the drop-down menu for the toolbar button in the composition window.

Thanks,

Jonathan

**Comment by sphh** [comment]
I still have this problem, but I still have the old version of LaTeXIt. I'll wait for the new version to hit the official Thunderbird's add-on repository and report back.

**Comment by protz** [comment]
And once you are on Thunderbird 68. Screenshots might help too... thanks!
