### ISSUE TITLE
Use dvipng when available

### ISSUE THREAD

**Issue by protz** [protz/LatexIt#4]
Should be much simpler & faster too

**Comment by janakelarsson** [comment]
I agree. This should be possible as a straight drop-in. Ask if you have questions on usage or need something fixed in it.

**Comment by FrankEular** [comment]
I wonder whether it is better to convert to svg files: dvisvgm will do the work.

**Comment by sphh** [comment]
As @Reylocnier found in #30, the default installation of ImageMagick has a tightened security which makes convert to fail. Using `dvipng` would get rid of this problem.

According to feraudyh in https://sourceforge.net/projects/dvipng/#project-reviews, dvipng is included in MikTeK for Windows, so for Windows users it's even easier (no need to install the ImageMagick package). Linux users have to install the dvipng package.

**Comment by msprotz** [comment]
I think the reason why I didn't use dvipng by default is that dvips had a concept of a bounding-box which allowed me to crop the image to the right dimensions. I remember I couldn't trivially find a way to achieve this with dvipng. That was, however, nearly 10 years ago.

Does anyone have a good dvipng invocation that would give me an equation cropped to the right dimensions or better, a pull request that achieves that? If the latter gets submitted, I would have no reason not to accept it, and would happily switch the rendering pipeline to dvipng.

Thanks,

jonathan

**Comment by janakelarsson** [comment]
What is the "right dimensions"? 
Does '-T tight' do what you want (crop to ink)?

**Comment by standard-two-simplex** [comment]
Using the standalone class I manage to get correct cropped dvi images, which then are correctly converted to pgn with `dvipng`.

Latex the document
```
\documentclass{standalone}
\begin{document}
$x=2$
\end{document}
```
Then run `dvipng` on the resulting dvi.
Example,
```
latex test.tex
dvipng -D 150 test.dvi
```
The `standalone` pacakage is easy to install and `dvipng` is shipped with Miktex. I don't know about other distributions, but it seems very few external dependencies.
I haven't programmed for Thunderbird, so I feel a little bit daunted to test and make a pull request.

**Comment by sphh** [comment]
As @janakelarsson mentioned, `dvipgn` with the `-T tight` option seems to work.

Here is a quick fix to use the single-step conversion with `dvipng` instead of the dual-step conversion `dvips`/`convert`. (This step-by-step procedure is Linux centric...):

1. Save the script below to a place to your liking, e.g. in a location in your path under the name `tblatex-dvipng`.
2. Make the script executable (`chmod +x </path/to/the/script>`).
3. Change the LatexIt! configuration:
    a. `Path to latex executable`: Leave unchanged
    b. `Path to dvips executable`: `<path/to/the/script>` (change to wherever you saved the script)
    c. `Path to convert executable`: `<path/to/the/script>` (change to wherever you saved the script)
    d. `Resolution (dpi)`: As desired

This worked for me ... If this works, I am happy to make a pull request which uses `dvipng` directly.

Here is the script:
```sh
#!/bin/sh
#
# Surrogate dvips command for LatexIt!
#
# This replaces the dvips executable for LatexIt!, but uses dvipng.
#
# Settings:
# Path to latex executable:     <not changed>
# Path to dvips executable:     <path/to/this/script>
# Path to convert executable:   /bin/true

# Path to dvipng executable (adapt to your liking)
DVIPNG=/usr/bin/dvipng

# These are the command originally called:
#   /usr/bin/dvips -o /tmp/tblatex-1.ps -E /tmp/tblatex-1.dvi
#   /usr/bin/convert -units PixelsPerInch -density 150 /tmp/tblatex-1.ps -trim /tmp/tblatex-1.png


if test $# -eq 4; then
    # Called as dvips!

    DVI=$4
    # Base filename including path
    FILE=$(echo "${DVI}" | cut -f 1 -d '.')

    # Make a backup copy of the .dvi file, because LatexIt! deletes this file
    # after running this command.
    cp ${DVI} ${FILE}.dvi~

    # Don't convert yet, but exit successfully
    exit 0

elif test $# -eq 7; then
    # Called as convert!

    DPI=$4
    PS=$5
    PNG=$7
    # Base filename including path
    FILE=$(echo "${PNG}" | cut -f 1 -d '.')

    # LatexIt! expects the .ps file to exist, let's create it
    touch ${PS}

    # Convert the dvi to png
    ${DVIPNG} -T tight -D ${DPI} -o ${PNG} ${FILE}.dvi~
    EXIT_CODE=$?

    # Remove backup copy of the .dvi file
    rm -f ${FILE}.dvi~

    exit ${EXIT_CODE}

fi

# We should never come here!
exit 1
```

**Comment by sphh** [comment]
Now there is a pull request #35 which uses dvipng (without the `standalone` class)...

**Comment by msprotz** [comment]
Wonderful! I'll take a look at the pull request and will give it a go under osx. I ran a quick test on my osx machine and it seems that mactex (which is texlive under the hood, I believe, does have dvipng).

Thanks,

Jonathan
