### ISSUE TITLE
Incompatible with Thunderbird 60.8.0

### ISSUE THREAD

**Issue by sphh** [protz/LatexIt#41]
When I try to install this add-on through the thunderbird's add-on page, I only get version 0.6.7.

When trying to install this add-on from https://jonathan.protzenko.fr/latex-it/latex-it-201909230754.xpi, I get the error message `LaTeX It! could not be installed because it is not compatible with Thunderbird 60.8.0."

Would it be possible to make the version 0.6.8 compatible with older version of Thunderbird? I am on the newest Linux Mint distribution and it might be some time that Thunderbird gets updated to version 68 ...

**Comment by protz** [comment]
Hey @sphh 

I seem to remember I made some backwards-incompatible changes that would require more work to make them compatible with both 60 and 68.

Someone on the Thunderbird mailing-list mentioned that there was a way for an addon to have two versions, one for 68 and one for 60. Would you be ok with the old version (without `dvipng`) remaining available? Or are you asking for the new version with dvipng to be made backwards-compatible?

**Comment by sphh** [comment]
I developed my pull request #35 on TB 60.x, so it should be able to apply it on the pre-webextension version 0.6.7. If there is the possibility to have the two versions for 60 and 68 in one extension, that would be really great! I have no idea, how that works.

On the other hand, maybe downloadable version for TB 60 which uses `dvipng` would be enough (but far from elegant!) ...

**Comment by sphh** [comment]
I am on TB 68.4.1 and LaTeXIt! works, so I close this issue.
