### ISSUE TITLE
works for equations embedded into the note, but 'insert complex LaTeX' fails...

### ISSUE THREAD

**Issue by cooch17** [protz/LatexIt#43]
Using T'Bird 68.4.1 (for better or worse). Have been using LatexIt for years, successfully, without issues, but for TBird versions pre-68.x.x. 

The issue with 68.4.1 (and perhaps 68.x.x generally) is simple enough. If I type (say) $x=yz$ into the body of an email, and click the LatexIt button, works fine. The formula is parsed, png file of same created, and popped into the note.

But, if I try to 'insert complex LaTeX', no so much. Nothing...happens. No log or debug file generated. Nothing.  I've attached a screen capture of the TBLatex  options popup window. Nothing looks awry, but I guarantee that clicking the 'OK' button does nothing. And, 'clicking 'OK', and then trying the 'LatexIt' button after the fact does nothing either. 
![latexit_complex](https://user-images.githubusercontent.com/4500611/72856022-56a31000-3c87-11ea-8325-a7c9c6e9086b.jpg)

**Comment by cooch17** [comment]
I just confirmed this on TBird under GNU/Linux (CentOS and Mint), and WIn 10 (Pro, and Home). Basically, the 'ok' button on the 'insert complex LaTeX'  dialog template doesn't do...anything. No new file is created in \temp, Nada.

**Comment by msprotz** [comment]
Thanks for the report. Do you observe anything in Tools > Developer Tools > Error Console?

**Comment by cooch17** [comment]
Not a thing. I fired up TBird, cleared out all the stuff from the Error Console (always astounds me how many errors emrge just from starting TBird), and then, created a note, and tried to insert a 'complex LaTeX' equation. Nothing. Didn't work, and absolutely nothing was redirected to the console. Its almost as if the 'OK' button in the 'insert complex Latex' windows isn't coupled to any action (like, creating a button in JavaScript, but not hooking it to a function). 

Same story on all 4 platforms I work on (Mint, CentOS, Win 10 Pro, Win 10 Home). All running 68.4.1. 

Even tried restarting TBird after disabling all the other addons I have (don't have many, but some), leaving LatexIt as the only active plugin. Made no difference. 

Again, whats weird is that if I enter a simple TeX equation into the body of the note (say, $rN$), then run LatexIt, works fine. Simply not for 'insert complex Latex''. If I run LatexIt on an equation embedded into the note, here is what the log looks like (from one of my Win 10 machines) - no error messages, all works fine. 

      > *** Found expression $rN$

      $PATH is C:\Program Files (x86)\Mozilla Thunderbird;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\ImageMagick-7.0.8-Q16;;;C:\Rtools\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\gnuplot\bin;C:\Users\abcdef\AppData\Local\Microsoft\WindowsApps;C:\Users\egc\Desktop\egc\text\MikTeX\miktex\bin\x64\

     *** Generating LaTeX expression:
     \documentclass[10pt]{article}
     \usepackage[utf8x]{inputenc}
     \usepackage{amsmath,bm,mathtools}
     \everymath{\displaystyle}
     \pagestyle{empty}

     \begin{document}
     $rN$ %this is where your LaTeX expression goes
     \end{document}

     I ran C:\Users\abcdef\Desktop\abcdef\text\MikTeX\miktex\bin\x64\latex.exe -output- 
    directory=C:\Users\abcdef\AppData\Local\Temp -interaction=batchmode 
     C:\Users\egc\AppData\Local\Temp\tblatex-4.tex error code 0
     I ran C:\Users\abcdef\Desktop\abcdef\MikTeX\miktex\bin\x64\dvipng.exe -T tight -D 115 -o 
     C:\Users\abcdef\AppData\Local\Temp\tblatex-4.png C:\Users\egc\AppData\Local\Temp\tblatex-4.dvi
     *** Status is 0
     *** Path is C:\Users\abcdef\AppData\Local\Temp\tblatex-4.png
     --> Replacing node... done

**Comment by oscarp-g** [comment]
Same here, Linux Mint 19.3. Any news?

**Comment by cooch17** [comment]
Mint was one of the distros I mentioned in the followup to my original report. I've also tried a few other distros. Basically, it isn't an OS-specific issue -- its an issue with the challenges of getting new addon extensions to work with TB 68.x.x.  I know that authors of some other extensions I've used in the past have basic given up.

**Comment by oscarp-g** [comment]
I guess that a workaround is to insert the LaTeX between double $$ on a new line? Seems to work.
