### ISSUE TITLE
Failed to generate images due to 'preview' package missing

### ISSUE THREAD

**Issue by lluisalemanypuig** [protz/LatexIt#76]
I've been using LatexIt! (0.7.3) for quite a while and I must it proved really useful while it worked. I'm using it on Thunderbird 68.10.0 (64-bit) and on Ubuntu 20.04. So far it's been working well, but it stopped working.

If I put a simple a formula as "$\pi$" in the email's body, it fails with 
![javascript_error](https://user-images.githubusercontent.com/12448652/97674144-542edb80-1a8d-11eb-8c9a-97c0a2c50b1a.png)

Well, I expected to see the 'lowercase' Greek letter pi, but instead, I see this
![email](https://user-images.githubusercontent.com/12448652/97675310-601b9d00-1a8f-11eb-85d8-e73448b63c54.png)

The configuration dialog is
![conf_dialog](https://user-images.githubusercontent.com/12448652/97674224-73c60400-1a8d-11eb-8653-c995c9d6ae57.png)

I followed the detailed troubleshooting and in the `convert` step I get the following error:
```
convert-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
convert-im6.q16: no images defined `/tmp/test.png' @ error/convert.c/ConvertImageCommand/3258.
```
After fixing this following the solution explained [here](https://stackoverflow.com/a/53180170/12075306), I get the error
```
convert-im6.q16: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/tmp/test.png' @ warning/png.c/MagickPNGWarningHandler/1667.
```

For this I could not find a solution that does not involve changing the command `convert -units PixelsPerInch /tmp/test.ps -trim /tmp/test.png`, so I assumed those solutions don't help here. Strange this is that the addon is complaining that it can't find the `preview` package and that I should insert a line `\usepackage[active,displaymath,textmath]{preview}` in the preamble of the LaTeX expression. But there already is a line like that. Moreoever, I tried including the `preview` package in the three different places where you can put it in the preamble but none of them fixed the problem.

The `preview` package is installed [to the latest version](https://www.ctan.org/pkg/preview), and the tex code
```
\documentclass{article}
\usepackage[utf8x]{inputenc}
\pagestyle{empty}
\usepackage[active,displaymath,textmath]{preview}
\begin{document}
$\pi$ %this is where your LaTeX expression goes
\end{document}
```
in a `test.tex` file is compiled with `pdflatex test.tex` without errors or warnings:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/share/texlive/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/share/texlive/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/share/texmf/tex/latex/preview/preview.sty
(/usr/share/texlive/texmf-dist/tex/generic/luatex85/luatex85.sty))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def)
No file test.aux.
(/usr/share/texlive/texmf-dist/tex/latex/ucs/ucsencs.def)
Preview: Fontsize 10pt
Preview: PDFoutput 1
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./test.aux) )</usr/shar
e/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb>
Output written on test.pdf (1 page, 8261 bytes).
Transcript written on test.log.
```

Any help will be appreciated.

**Comment by sphh** [comment]
Thanks for the extensive bug report.

I tried to use your LaTeX template and get the same problem. The only difference to my template is the line
```latex
%&latex
```
If you remove this line, it should work again (if you change your latex executable from `/usr/bin/pdflatex` back to `/usr/bin/latex`!)

At the moment, do NOT put any comment BEFORE the line with the `preview` package.

I will look into it, why comments before the `preview` package makes the check for it to fail.

BTW you can use
```latex
\usepackage[utf8]{inputenc}
```
(note the removed `x` from the option `utf8x`), which reduces the required dependencies on Debian systems.

Please also note, that the wiki is a bit outdated.

**Comment by lluisalemanypuig** [comment]
Yes, it works again. Removing the comment and changing the executable did the trick. Thank you.
