### ISSUE TITLE
Ubuntu users need to install texlive-latex-extra for utf8x to work..

### ISSUE THREAD

**Issue by drevicko** [protz/LatexIt#8]
This probably happens on other linux flavors too...

It would be good to check that texlive-latex-extra (or whichever part of that package that gives you utf8x) is installed along with the latex, convert, etc.. binaries

**Comment by sphh** [comment]
9 years later ...

@protz, do you think we should/can use `utf8` instead of `utf8x`? This might be a good discussion regarding this topic: https://tex.stackexchange.com/questions/13067/utf8x-vs-utf8-inputenc

**Comment by protz** [comment]
As always egreg's answer is illuminating and definitely means that we should switch to utf8. Please go ahead, thanks!

**Comment by sphh** [comment]
The option to the `inputenc` package was changed from `utf8x` to `utf8` in PR #58, removing the dependency of this add-on on `texlive-latex-extra` (on Debian and maybe other systems).
